### ISSUE TITLE
Multiple errors with vagrant up 

### ISSUE THREAD

**Issue by patocabo** [rofrano/vagrant-docker-image#13] opened 2022-05-04 12:02 UTC
I set up everything as the repo said, and I keep receiving this log errors:

```
    report: Need to get 31.9 MB of archives.
    report: After this operation, 244 kB disk space will be freed.
    report: Do you want to continue? [Y/n] Abort.
    report: E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
    report: E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation
    report: deb http://apt.postgresql.org/pub/repos/apt/ jammy-pgdg main
    report: /tmp/vagrant-shell: line 7: deb: command not found
    report: sudo: apt-add-repository: command not found
    report: Hit:1 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
    report: Get:2 http://apt.postgresql.org/pub/repos/apt jammy-pgdg InRelease [86.6 kB]`
```

thats just a few errors but I have tons of bugs after those

**Comment by rofrano** [comment] 2022-05-05 11:45
@patocabo Can you post your `Vagrantfile` and I'll see if I can reproduce the error locally. If you are using a VPN disable it. I've seen lots of failures from VPN's getting in the way of downloading packages. Also please use 3 back-ticks (```) when formatting output. Thanks.

**Comment by patocabo** [comment] 2022-05-05 11:48
hey @rofrano sure! this is it:

```# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "ubuntu"
  config.vm.provision :shell, :path => "misc/all.sh"
  config.ssh.keep_alive = true
  config.ssh.insert_key = false
  config.vm.boot_timeout = 300


  config.vm.provider :docker do |docker, override|
    override.vm.box = nil
    docker.image = "rofrano/vagrant-provider:ubuntu"
    docker.remains_running = true
    docker.has_ssh = true
    docker.privileged = true
    docker.volumes = ["/sys/fs/cgroup:/sys/fs/cgroup:rw"]
    docker.create_args = ["--cgroupns=host"]
    # Uncomment to force arm64 for testing images on Intel
    #docker.create_args = ["--platform=linux/arm64"]     
  end  

    config.vm.define :report do |report|
      report.vm.box = "ubuntu/bionic64"
      report.vm.hostname = 'local.equidam.com'
      report.vm.network "private_network", ip: "10.250.25.10"
      # report.vm.network "forwarded_port", guest: 80, host: 80
      # report.vm.network "forwarded_port", guest: 443, host: 443
      report.vm.network "forwarded_port", guest:5432 , host: 5432,
      auto_correct: true

    end


end
```
Actually the vm boots find, but I'm not being able to run the bash script after that

```

apt-get update
apt-get upgrade
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 7FCC7D46ACCC4CF8
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
RELEASE=$(lsb_release -cs)
echo "deb http://apt.postgresql.org/pub/repos/apt/ ${RELEASE}"-pgdg main | tee  /etc/apt/sources.list.d/pgdg.list
deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main
#sudo add-apt-repository ppa:ondrej/php
sudo LC_ALL=C.UTF-8 apt-add-repository -y ppa:ondrej/php

apt-get update

apt-get install \
    nginx \
    php7.3 \
    php7.3-fpm \
    php7.3-pgsql \
    php7.3-curl \
    php7.3-dom \
    php7.3-zip \
    php7.3-gd \
    php7.3-mbstring \
    openssl \
    build-essential \
    python-setuptools \
    python-pip \
    python-dev \
    supervisor \
    npm \
    libjsoncpp1 \
    lsb-release \
    postgresql-11 \
    python-pip \
    gunicorn \
    autogen \
    autoconf \
    libtool \
    ruby \
    -y

# install newest version of composer
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php composer-setup.php
php -r "unlink('composer-setup.php');"

sudo php composer-setup.php --install-dir=/usr/bin --filename=composer

pip install --upgrade pip

# make the equidam users
getent passwd equidam || adduser --disabled-password --gecos "" equidam

# install and run of the ten_qs_comparitor
echo " install pyhton packages!!!"
sudo pip install gunicorn flask pandas
su equidam -c 'mkdir -p /home/equidam/ten_qs/{tmp,logs}'

# change the path for the dev envi
cat > /etc/supervisor/supervisord.conf << EOL
; supervisor config file

[unix_http_server]
file=/var/run/supervisor.sock   ; (the path to the socket file)
chmod=0700                       ; sockef file mode (default 0700)

[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)

; the below section must remain in the config file for RPC
; (supervisorctl/web interface) to work, additional interfaces may be
; added by defining them in separate rpcinterface: sections
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; use a unix:// URL  for a unix socket

; The [include] section can just contain the "files" setting.  This
; setting can list multiple files (separated by whitespace or
; newlines).  It can also contain wildcards.  The filenames are
; interpreted as relative to this file.  Included files *cannot*
; include files themselves.

[include]
files = /etc/supervisor/conf.d/*.conf

[program:ten_qs_comparitor]
command=/usr/bin/gunicorn -c /vagrant/tenq/gunicorn_config.py wsgi:app
directory=/vagrant/tenq
user=equidam
autostart=true
autorestart=true
EOL

service supervisor restart
supervisorctl restart ten_qs_comparitor

# grunt minifer and watch
sudo npm install -g grunt-cli
sudo npm install grunt-contrib-sass --save-dev
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
cd /vagrant/grunt/; npm install
sudo ln -s /usr/bin/nodejs /usr/bin/node
sudo chmod -R 777 /usr/local/rvm/gems/
gem update
gem install compass
gem install sass

sleep 4
su - ubuntu -c 'cd /vagrant/grunt/; grunt &> /home/vagrant/grunt.log &' 
echo "============= if the grunt is running you wil see it here ====="
ps -aux | grep grunt
# for the sass and javascript compilers


rm -f /etc/nginx/sites-enabled/default
cp /vagrant/misc/nginx-config/local.equidam.com.conf /etc/nginx/conf.d
cp /vagrant/misc/nginx-config/app.equidam.test.conf /etc/nginx/conf.d
cp /vagrant/misc/nginx-config/www.equidam.test.conf /etc/nginx/conf.d
# cp /vagrant/misc/nginx-config/.equidam.dev.conf /etc/nginx/conf.d
cp /vagrant/misc/nginx-config/proxy_params /etc/nginx/
cp /vagrant/misc/nginx-config/nginx.conf /etc/nginx/

mkdir -p /etc/ssl/equidam/
cat > /etc/ssl/equidam/equidam.key << EOL
-----BEGIN PRIVATE KEY-----
{private key}
-----END PRIVATE KEY-----

EOL

cat > /etc/ssl/equidam/equidam.crt << EOL
-----BEGIN CERTIFICATE-----
{private key}

-----END CERTIFICATE-----

EOL

/etc/init.d/nginx restart

echo "host     sameuser        all             127.0.0.1/32       md5" >> /etc/postgresql/11/main/pg_hba.conf
echo "host     sameuser        all             10.250.25.10/32    md5" >> /etc/postgresql/11/main/pg_hba.conf
echo "host     all             all             10.0.2.2/32        md5" >> /etc/postgresql/11/main/pg_hba.conf

sed -i "s/#listen_addresses =.*/listen_addresses = '*'/" /etc/postgresql/11/main/postgresql.conf
/etc/init.d/postgresql restart

su postgres -c "echo \"create database equidam; create role equidam login password '1234';\" | psql"
su postgres -c "echo \"GRANT ALL PRIVILEGES ON DATABASE equidam TO equidam;\" | psql"
su postgres -c "echo \"alter user equidam with superuser ;\" | psql"

touch /home/equidam/.pgpass
chmod 600 /home/equidam/.pgpass
chown equidam: /home/equidam/.pgpass

cat > /home/equidam/.pgpass << EOL
127.0.0.1:5432:equidam:equidam:1234
EOL

grep PGHOST=127.0.0.1 /home/equidam/.bashrc || cat >> /home/equidam/.bashrc << EOL
export PGHOST=127.0.0.1
EOL

su postgres -c 'psql -d equidam < /vagrant/localdump/cleandump'
su postgres -c "echo \"alter user equidam with nosuperuser ;\" | psql"

echo '127.0.0.1 localhost' > /etc/hosts
echo "10.250.25.10 local.equidam.com" >> /etc/hosts
echo "10.250.25.10 laquidam.test" >> /etc/hosts
echo "10.250.25.60 printerlocal.equidam.com" >> /etc/hosts

sudo mkdir /home/equidam/geoip

sudo cp /vagrant/misc/GeoLite2-City.mmdb /home/equidam/geoip/

mkdir /vagrant/log
sudo chmod -R 777 /vagrant/log
echo "=========================== DONE ==========================="

```

**Comment by rofrano** [comment] 2022-05-05 12:18
@patocabo OK, I'm seeing he same thing with your script. Let me look into this. Thanks!

**Comment by patocabo** [comment] 2022-05-05 12:27
thank you so much for your time john! I've been trying to set up my local environment for a new job and I'm stuck with this, it's been a truly pain. I'm actually consider buying a new laptop with linux only because of this haha.

**Comment by rofrano** [comment] 2022-05-07 18:05
Hi @patocabo , I've looked into this and the news isn't good. The software you want to install will not install on any version of Ubuntu newer than Bionic. Unfortunately, Bionic is too old to work with the `systemd` image that I'm creating. I tried creating a bionic version of my vagrant provider but I get this error when I bring it up because `/usr/sbin/init` isn't being created:

```
A Docker command executed by Vagrant didn't complete successfully!
The command run along with the output from the command is shown
below.

Command: ["docker", "run", "--name", "vagrant-docker-provider_default_1651943555", "-d", "-p", "127.0.0.1:2204:22", "-v", "/sys/fs/cgroup:/sys/fs/cgroup:rw", "-v", "/Users/rofrano/GitHub/rofrano/vagrant-docker-provider:/vagrant", "--privileged", "-h", "ubuntu", "--cgroupns=host", "vagrant-provider:bionic", {:notify=>[:stdout, :stderr]}]

Stderr: docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/sbin/init": stat /usr/sbin/init: no such file or directory: unknown.


Stdout: 7f8b20de0c9bfb3b92ce61269ab6a7d1bcac0206e550e8ccc1ac50c0e90b7849
```

I'm guessing that somewhere between Bionic 18.04 and Focal 20.04 the software you want to install stopped working because Python 2 is required by your installers and Python 2 support was dropped. I couldn't even get your software stack to install on a VirtualBox VM of Focal so this has nothing to do with the Docker provider (it failed in the same way).

There are three solutions:
1. Figure out a way to get Bionic 18.04 working as a Docker provider image for Vagrant. 
2. Upgrade your stack to run on at least Focal 20.04 and use my `rofrano/vagrant-provider:focal` image
3. Use `multiplass` instead of `vagrant`. 

I have been unsuccessful in figuring out the first option. Others should feel free to work on this and send me a Pull Request. If I were you I would work on option 2. Python 2 has been out of service for 2 years now. Maybe it's time to update the stack.

There is also option 3:

> I'm actually consider buying a new laptop with linux only because of this haha.

There is absolutely no need to do that. You can use [multipass](https://multipass.run) to create real VMs. I tested it with your shell script above and it works fine on my Apple M1 Mac mini. 

Just `brew install multipass` and then:

```bash
multipass launch bionic --name bionic
multipass mount . bionic:/vagrant
multipass shell bionic
```

This will download a Bionic image and start a VM it giving it the name *bionic*. Then it will share the current folder inside the multipass VM as `/vagrant` (which is what you are expecting). The last line will shell into the bionic image (i.e., `vagrant ssh` == `multipass shell`). BTW, multipass also supports `cloud-init` to automate provisioning just like Vagrant. I'm currently investigating is as a replacement for vagrant in my toolkit since it works great on Apple M1. 

That is way cheaper than buying a new laptop. ;-)

**Comment by patocabo** [comment] 2022-05-09 21:23
You are awesome john! Thank you so much!! I had a few errors with some packages like composer for example, but I installed them manually in my vm. The last question, do you know how I do I do to access an internal ip (in vm) from the host of (mac m1) ?

**Comment by rofrano** [comment] 2022-05-10 11:27
If you are referring to `multipass` you can use the `list` command to list the VM's with their IP addresses:

```bash
$ multipass list

Name                    State             IPv4             Image
bionic                  Running           192.168.64.2     Ubuntu 18.04 LTS
```

The address of my _bionic_ VM is `192.168.64.2`

```bash
$ ping 192.168.64.2
PING 192.168.64.2 (192.168.64.2): 56 data bytes
64 bytes from 192.168.64.2: icmp_seq=0 ttl=64 time=0.300 ms
64 bytes from 192.168.64.2: icmp_seq=1 ttl=64 time=0.531 ms
64 bytes from 192.168.64.2: icmp_seq=2 ttl=64 time=0.465 ms
```

**Comment by rofrano** [comment] 2022-10-09 19:32
Closing this issue as it looks to be resolved.

**Closed as completed by rofrano** 2022-10-09 19:32 UTC

**Comment by patocabo** [comment] 2022-10-10 13:33
I resolved it with Parallels desktop, thank you john!

**Comment by rofrano** [comment] 2022-10-10 20:25
Great to know. Thanks for sharing that. Sorry multipass didn't work out for you but Parallels is great too.
